site_name: ReadTheDocs sandbox for best practice
nav:
  - Home: 'index.md'
  - Gitlab: 'best_practice.md'
  - Infrastructure: 'hpc_servers.md'
theme: readthedocs
repo_url: https://github.com/vincentrose88/readthedocs_sandbox
extra_css:     
  - 'css/tailored.css'