site_name: AIDR Best Practice
nav:
  - Home: 'index.md'
  - Gitlab: 'best_practice.md'
  - Infrastructure: 'hpc_servers.md'
  - 'Tech Stack': 'tech_stack.md'
theme: 
  name: readthedocs
  logo: 'css/nn_logo.png'
# name: mkdocs
#  color_mode: dark
#  user_color_mode_toggle: true
#  nav_style: auto
repo_url: https://github.com/vincentrose88/readthedocs_sandbox
extra_css:     
  - 'css/tailored.css'
