site_name: ReadTheDocs sandbox for best practice
nav:
  - Home: 'index.md'
  - Gitlab: 'best_practice.md'
  - Infrastructure: 'hpc_servers.md'
theme: 
#  name: readthedocs
#  logo: docs/css/NVO.D.svg
  name: mkdocs
  color_mode: dark
  user_color_mode_toggle: true
  nav_style: dark
repo_url: https://github.com/vincentrose88/readthedocs_sandbox
extra_css:     
  - 'css/tailored.css'
